### PR TITLE
Use custom version of es6-collections with support for Safari 7.1 & 8

### PR DESCRIPTION
**Pull request by adius**

### CODE REVIEW

**Comment by Steditor** [comment]
See https://github.com/brickify/es6-collections/commit/8e7dc71cbc6fc6205c4245ada06ab8a5a13345f1#commitcomment-12009655

**Comment by Steditor** [comment]
@adius can you check whether [this](https://github.com/Steditor/es6-collections-iterators/commit/267d9b776091690059d4be68a22ff2fe8f8851cb) works?

**Comment by adius** [comment]
I'll be there in 10 min. Then I can check. But isn't safari also available for windows?

**Comment by AtiX** [comment]
nope

**Comment by Steditor** [comment]
We checked on a HCI Mac now - works as expected.

**Comment by Steditor** [comment]
Will be replaced by a new version of #705

**Pull request closed without merging**
