### PR TITLE
Feature/part list in editor

### LINKED ISSUE #569: Show part list in online build instructions?
I think it's a cool feature and should not only be in the download instructions?

### LINKED ISSUE #601: show detailed part list as a pop up
..when hovering / clicking on the brick counter in the workflow UI

### PR DESCRIPTION
**Pull request by AtiX**
Closes #569 
Closes #601

### CODE REVIEW

**Comment by AtiX** [comment]
:trumpet: Trööt! :trumpet:

**Comment by AtiX** [comment]
@Steditor :trumpet: trööt!

**Comment by Steditor** [comment]
probable follow-ups: #616 and #617

**Comment by johannesdeselaers** [comment]
:ship:

**Pull request merged**
