### PR TITLE
Feature/fix ie es6 collections

### LINKED ISSUE #704: Internet Explorer does not fully support es6 collections
E.g. the `values`, `keys`, `entries` functions are missing.

### LINKED ISSUE #706: Broken in Safari
No model gets displayed in safari

### PR DESCRIPTION
**Pull request by Steditor**
Closes #704 
Closes #706

### CODE REVIEW

**Comment by johannesdeselaers** [comment]
the code looks alright and on mac using safari/chrome everything remains intact, but I have no way of testing on IE - which is the point of this pull request
can you take a look @stuikomma?

**Comment by adius** [comment]
@johannesdeselaers Was für einen alten Safari benutzt du denn, dass es bei dir damit funktioniert 😂

**Comment by Steditor** [comment]
See https://github.com/WebReflection/es6-collections/issues/27 - I'm not exactly a fan of forcing the polyfill over the native implementation, let's have a look at what Safari exactly does tomorrow.

**Comment by stuikomma** [comment]
Looks fine on IE 11.

**Pull request merged**
