### PR TITLE
Feature/three pointer controls

### LINKED ISSUE #526: Switch to three-pointer-controls
See https://github.com/brickify/three-pointer-controls

### PR DESCRIPTION
**Pull request by Steditor**
Adds touch support to brickify.

Works best in Chrome and Internet Explorer (you need #705 for IE), Firefox at the moment does not allow to prevent the default pinch gesture, that therefore conflicts with navigation.

Closes #526 
Closes #703

### CODE REVIEW

**Comment by adius** [comment]
When I change the view on the landing page, the model does not start to rotate again afterwards.
Is this intended?

**Comment by adius** [comment]
…otherwise seems to be fine :boat:

**Comment by Steditor** [comment]
Inteded behavior, but that can be changed easily tomorrow - I just realized that the current controls continue rotating.

**Comment by stuikomma** [comment]
Looks fine to me on IE 11. Merged `feature/fix_IE_es6-collections` locally as you proposed.

**Comment by Steditor** [comment]
@adius already gave me a :boat:

**Pull request merged**
