### PR TITLE
New arrow and improved quickconvert buttons

### PR DESCRIPTION
**Pull request by adius**

### CODE REVIEW

**Comment by AtiX** [comment]
the new arrow does not look better.

:no_entry:

**Comment by stuikomma** [comment]
Neither looks good imo.

**Comment by adius** [comment]
I doubt that any one will look good.
How about simply removing it.
I don't think it conveys much meaning anyway…

**Comment by Steditor** [comment]
:-1: 
I like the old one, and it does convey meaning - quite a lot of people at the maker faire understood the conversion process due to the arrow.
I'd vote for rejecting the pull request and keeping the old arrow.
Can you extract the parts that do not deal with the arrow to a new PR?

**Comment by AtiX** [comment]
Closed. See issue #607

**Pull request closed without merging**
